catalogo/catalogo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('videojuego.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalogo/videojuego/urls.py
from .views import inicio, incio_admin, PlataformasCreate, VideoJuegoCreate, VideojuegoList, VideojuegoUpdate, VideojuegoDelete, VideoJuegoDetalle, SearchResultsView, PlataformasList, BuscarPlataformas, PlataformasDetalle, PlataformasUpdate, PlataformasDelete
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from .views import upload_file
from django.conf.urls import url, include



urlpatterns = [
    path('',inicio , name='inicio'),
    path('index_admin/', incio_admin, name='inicio_admin'),
    #---------------------------------------URL PLATAFORMAS------------------------------------
    path('crear_plataformas/',PlataformasCreate.as_view(), name='crear_plataformas'),
    path('listar_plataformas/',PlataformasList.as_view(), name='listar_plataformas'),
    path('buscar_plataformas/',BuscarPlataformas.as_view(), name='buscar_plataformas'),
    path('detalle_plataformas/<int:pk>', PlataformasDetalle.as_view(), name='detalle_plataformas'),
    path('actualizar_plataformas/<int:pk>', PlataformasUpdate.as_view(), name='actualizar_plataformas'),
    path('eliminar_plataformas/<int:pk>', PlataformasDelete.as_view(), name='eliminar_plataformas' ),

    #---------------------------------------URL VIDEOJUEGOS------------------------------------
    path('crear_videojuego/', VideoJuegoCreate.as_view(),name='crear_videojuego'),
    url('cargar', upload_file, name='cargar_imagen'),
    path('listar_videojuego/', VideojuegoList.as_view(), name='listar_videojuego' ),
    path('actualizar_videojuego/<int:pk>', VideojuegoUpdate.as_view(), name='actualizar_videojuego' ),
    path('eliminar_videojuego/<int:pk>', VideojuegoDelete.as_view(), name='eliminar_videojuego' ),
    path('detalle_videojuego/<int:pk>', VideoJuegoDetalle.as_view(), name='detalle_videojuego'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo/videojuego/models.py
from django.db import models


# Create your models here.

class Plataformas(models.Model):
    LISTA_TIPO = (
        ('c','consola'),
        ('p','pc'),
        ('m','movil')
    )
    marca = models.CharField(max_length=30)
    fabricante = models.CharField(max_length=30)
    tipo = models.CharField(max_length=1, choices=LISTA_TIPO)
    generacion = models.CharField(max_length=30)
    capacidad_disco = models.CharField(max_length=30)
    gpu = models.CharField(max_length=30)
    soporte = models.CharField(max_length=30)
    web_oficial = models.URLField(max_length=200)

    def __str__(self):
        return self.marca + " - " +self.fabricante

class VideoJuego(models.Model):
    LISTA_GENERO = (
        ('a','accion'),
        ('d','deportes'),
        ('e','estrategia'),
        ('c','carreras')
    )

    LISTA_CLASIFICACION = (
        ('n','E10+(niño)'),
        ('a','T(Adolecente)'),
        ('m','M+17(Maduro)'),
        ('a','A0+18(Adulto)')
    )

    LISTA_JUGABILIDAD = (
        ('1','Primera Persona'),
        ('3','Tercera Persona')
    )

    nombre = models.CharField(max_length=100, unique=True, help_text='Ya existe el nombre del videojuego')
    genero = models.CharField(max_length=1, choices=LISTA_GENERO)
    fabricante = models.CharField(max_length=100)
    clasificacion = models.CharField(max_length=1, choices=LISTA_CLASIFICACION)
    ano_lanzamiento = models.DateField()
    max_jugadores = models.IntegerField()
    jugabilidad = models.CharField(max_length=1, choices=LISTA_JUGABILIDAD)
    #plataformas = models.ForeignKey(Plataformas, null=True, blank=True,on_delete=models.CASCADE)
    plataformas = models.ManyToManyField(Plataformas)
    web_oficial = models.URLField(max_length=200)
    imagen = models.FileField(upload_to='myFolder/', blank=True, null=True)
    trailer = models.URLField(max_length=200)
    ranking = models.DecimalField(max_digits=5, decimal_places=2)

    def only_year(self):
        return self.ano_lanzamiento.strftime('%Y')
    

    
    def __str__(self):
        return self.nombre

catalogo/videojuego/forms.py
from django import forms
from .models import Plataformas, VideoJuego

class PlataformasForms(forms.ModelForm):
    class Meta:
        model = Plataformas
        fields = ['marca','fabricante','tipo','generacion','capacidad_disco','gpu','soporte', 'web_oficial']
        labels = {
            'marca' : 'Marca',
            'fabricante' : 'Fabricante',
            'tipo' : 'Tipo',
            'generacion' : 'Generacion',
            'capacidad_disco' : 'Capacidad de disco',
            'gpu' : 'GPU',
            'soporte' : 'Soporte',
            'web_oficial' : 'Web oficial'

        }

        widgets = {

            'marca' : forms.TextInput(attrs={'class':'form-control'}),
            'fabricante' : forms.TextInput(attrs={'class':'form-control'}),
            'tipo' : forms.Select(attrs={'class':'form-control'}),
            'generacion' : forms.TextInput(attrs={'class':'form-control'}),
            'capacidad_disco' : forms.TextInput(attrs={'class':'form-control'}),
            'gpu' : forms.TextInput(attrs={'class':'form-control'}),
            'soporte' : forms.TextInput(attrs={'class':'form-control'}),
            'web_oficial' : forms.URLInput(attrs={'class':'form-control'}),
            
        }

class VideoJuegoForms(forms.ModelForm):

    class Meta:
        model = VideoJuego
        fields = [
            'nombre',
            'genero',
            'fabricante',
            'clasificacion',
            'ano_lanzamiento',
            'max_jugadores',
            'jugabilidad',
            'plataformas',
            'web_oficial',
            'imagen',
            'trailer',
            'ranking',
        ]
        labels = {

            'nombre' : 'Nombre',
            'genero' : 'Genero',
            'fabricante' : 'Fabricante',
            'clasificacion' : 'Clasificacion',
            'ano_lanzamiento' : 'Año de Lanzamiento',
            'max_jugadores' : 'Maximo de Jugadores',
            'jugabilidad' : 'Jugabilidad',
            'plataformas' : 'Plataformas',
            'web_oficial' : 'Web Oficial',
            'imagen' : 'Imagen',
            'trailer' : 'Trailer',
            'ranking' : 'Raking',

        }

        widgets = {

            'nombre' : forms.TextInput(attrs={'class':'form-control'}),
            'genero' : forms.Select(attrs={'class':'form-control'}),
            'fabricante' : forms.TextInput(attrs={'class':'form-control'}),
            'clasificacion' : forms.Select(attrs={'class':'form-control'}),
            #'ano_lanzamiento' : forms.DateField(attrs={'class':'form-control'}),
            'ano_lanzamiento' : forms.DateInput(attrs={'type' : 'data', 'class':'form-control'}),
            'max_jugadores' : forms.TextInput(attrs={'class':'form-control'}),
            'jugabilidad' : forms.Select(attrs={'class':'form-control'}),
            'plataformas' : forms.CheckboxSelectMultiple(),
            'web_oficial' : forms.TextInput(attrs={'class':'form-control'}),
            'imagen' : forms.FileInput(),
            'trailer' : forms.TextInput(attrs={'class':'form-control'}),
            'ranking' : forms.TextInput(attrs={'class':'form-control'}),
        }

catalogo/videojuego/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from .models import Plataformas, VideoJuego
from .forms import PlataformasForms, VideoJuegoForms
from django.db.models import Q

# -----------------------------------INICIO SIN LOGIN-----------------------------------------------
def inicio(request):
    top5 = VideoJuego.objects.order_by("-ranking")[:5]
    return render(request, 'index.html',{'top5':top5})
    #return render(request, 'index.html')

# -----------------------------------INICIO CON LOGIN-----------------------------------------------
def incio_admin(request):
    top5 = VideoJuego.objects.order_by("-ranking")[:5]
    return render(request, 'videojuego/admin.html',{'top5':top5})
    #return render(request, 'videojuego/admin.html')

# -------------------------------------PLATAFORMAS--------------------------------------------------

#************CREAR PLATAFORMAS****************
class PlataformasCreate(CreateView):
    model = Plataformas
    form_class = PlataformasForms
    success_url = reverse_lazy('inicio_admin')

#************LISTAR PLATAFORMAS****************
class PlataformasList(ListView):
    model = Plataformas

#************BUSCAR PLATAFORMAS****************
class BuscarPlataformas(ListView):
    model = Plataformas
    template_name = 'plataformas_list.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Plataformas.objects.filter(
            Q(marca__icontains = query) | Q(fabricante__icontains = query)
        )
        return object_list

#************DETALLE PLATAFORMAS****************
class PlataformasDetalle(DetailView):
    model = Plataformas

#************ACTUALIZAR PLATAFORMAS****************
class PlataformasUpdate(UpdateView):
    model = Plataformas
    form_class = PlataformasForms
    success_url = reverse_lazy('inicio_admin')

#************ELIMINAR PLATAFORMAS****************
class PlataformasDelete(DeleteView):
    model = Plataformas
    success_url = reverse_lazy('inicio_admin')


# -------------------------------------VIDEOJUEGOS--------------------------------------------------

#************CREAR VIDEOJUEGOS****************
class VideoJuegoCreate(CreateView):
    model = VideoJuego
    form_class = VideoJuegoForms
    success_url = reverse_lazy('inicio_admin')


#************SUBIR ARCHIVOS****************
def upload_file(request):
    if request.method == 'POST':
        form = VideoJuegoForms(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('inicio_admin')
    else:
        form = VideoJuegoForms()
    return render(request, 'videojuego/videojuego_form.html', {
        'form': form
    })

#************LISTAR VIDEOJUEGOS****************
class VideojuegoList(ListView):
    model = VideoJuego

#************DETALLE VIDEOJUEGOS****************
class VideoJuegoDetalle(DetailView):
    model = VideoJuego

#************ACTUALIZAR VIDEOJUEGOS****************
class VideojuegoUpdate(UpdateView):
    model = VideoJuego
    form_class = VideoJuegoForms
    success_url = reverse_lazy('inicio_admin')

#************ELIMINAR VIDEOJUEGOS****************
class VideojuegoDelete(DeleteView):
    model = VideoJuego
    success_url = reverse_lazy('inicio_admin')

#************BUSCAR VIDEOJUEGOS****************
class SearchResultsView(ListView):
    model = VideoJuego
    template_name = 'videojuego_list.html'

    def get_queryset(self):
        genero = None
        query = self.request.GET.get('q')
        query2 = self.request.GET.get('lista')
        object_list = VideoJuego.objects.filter(
            Q(nombre__icontains = query) |  Q(plataformas__marca__icontains = query)
        )
        if query2:
            genero = VideoJuego.objects.filter(genero__exact=query2)
            return genero
        return object_list

catalogo/templates/videojuego/admin.html
{% extends 'base.html' %}

{% block title %} IndexConLogin {% endblock %}

{% block menulogin %} 
{% load static %}


<a class="navbar-brand mr-auto mt-2" href="{% url 'inicio_admin' %}"> <img src="{% static 'img/moneda.png' %}" height="40" alt="">Inicio</a>

<div class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <img src="{% static 'img/estrella.png' %}" height="52" alt="">Gestión de Video Juegos</a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'crear_videojuego' %}">Creación de Video Juego</a>
        <a class="dropdown-item" href="{% url 'listar_videojuego' %}">Búsqueda de Video Juego</a>
        <div class="dropdown-divider"></div>
    </div>
</div>

<div class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <img src="{% static 'img/cubo.png' %}" height="43" alt="">Gestión de Plataformas</a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <a class="dropdown-item" href="{% url 'crear_plataformas' %}">Creación de Plataforma</a>
        <a class="dropdown-item" href="{% url 'listar_plataformas' %}">Búsqueda de Plataforma</a>
        <div class="dropdown-divider"></div>
    </div>
</div>

<div class="nav-item dropdown">

    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <img src="{% static 'img/yorshi_.png' %}" height="43" alt="">Sesion</a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        {% if user.is_authenticated %}
        <p>Usuario: {{ user.get_username }}</p>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="{% url 'logout' %}">Cerrar Sesion</a>
        <div class="dropdown-divider"></div>
        {% else %}
        <a href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block TOP5 %}

    {% for t5 in  top5 %}

    <!--
    {% if t5.imagen %}
    <img src="{{ t5.imagen.url }}" height="300">
    {% endif %}
    <p> {{ t5.ranking }} </p>
    -->

    <div class="row pt-3">



            <div class="col-sm-4">

                <div class="card" style="width: 18rem;">

                    {% if t5.imagen %}
                    <img src="{{ t5.imagen.url }}" height="300" class="card-img-top">
                    {% endif %}

                    <div class="card-body">    
                        <div class="ec-stars-wrapper">
                            <a href="#" style="color:gold;">&#9733;</a>
                            <a href="#" style="color:gold;">&#9733;</a>
                            <a href="#" style="color:gold;">&#9733;</a>
                            <a href="#" style="color:gold;">&#9733;</a>
                            <a href="#" style="color:gold;">&#9733;</a>
                        </div>
                      <p class="card-text">{{ t5.ranking }}</p>
                    </div>
                </div>

            </div>



            



    </div>

    

    {% endfor %}


{% endblock %}

catalogo/templates/videojuego/plataformas_confirm_delete.html
{% extends 'videojuego/admin.html' %}

{% block title %} Crear Plataformas {% endblock %}

{% block content %}
<br>

<form action="" method="post" class="bt-2">

    {% csrf_token %}


    <div class="card">
        <div class="card-header bg-warning text-white">
          <h4>Alerta</h4>
        </div>
        <div class="card-body">
          <h3 class="card-text">Esta seguro de eliminar la plataforma: {{ object }} del inventario ?</h3>
          <button class="btn btn-danger" type="submit" value="confirmacion">Confirmar</button>
        </div>
      </div>


</form>
<br>
{% endblock %}

catalogo/templates/videojuego/plataformas_detail.html
{% extends 'videojuego/admin.html' %}

{% block title %} Crear Plataformas {% endblock %}

{% block content %}

<h1 class="text-center text-primary">Detalle de Plataforma</h1>

<table border="1" cellpadding="8" cellspacing="0" class="table table-bordered">

    <tr>
        <th class="bg-secondary text-light">Marca</th>
        <td>{{ object.marca }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Fabricante</th>
        <td>{{ object.fabricante }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Tipo</th>
        <td>{{ object.get_tipo_display }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Generacion</th>
        <td>{{ object.generacion }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Capacidad de disco</th>
        <td>{{ object.capacidad_disco }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">GPU</th>
        <td>{{ object.gpu }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Soporte</th>
        <td> <a href="{{ object.soporte }}">{{ object.soporte }}</a> </td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Web oficials</th>
        <td><a href="{{ object.web_oficial }}">{{ object.web_oficial }}</a></td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Modificacion</th>
        <td>
            <a href="{% url 'actualizar_plataformas' object.id %}" class="btn btn-success">Actualizar</a><br>
            <a href="{% url 'eliminar_plataformas' object.id %}" class="btn btn-danger mt-3">Eliminar</a>
        </td>
    </tr>

</table>

{% endblock %}

catalogo/templates/videojuego/plataformas_form.html
{% extends 'videojuego/admin.html' %}

{% block title %} CrearPlataformas {% endblock %}

{% block content %}




<form method="post">

	{% csrf_token %}

    <div class="row h-100 justify-content-center align-items-center">
        <h1 class="text-primary">Formulario Crea Plataformas</h1>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.marca.name}}">{{form.marca.label}}</label>
				{{form.marca}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.fabricante.name}}">{{form.fabricante.label}}</label>
				{{form.fabricante}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.tipo.name}}">{{form.tipo.label}}</label>
				{{form.tipo}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.generacion.name}}">{{form.generacion.label}}</label>
				{{form.generacion}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.capacidad_disco.name}}">{{form.capacidad_disco.label}}</label>
				{{form.capacidad_disco}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.gpu.name}}">{{form.gpu.label}}</label>
				{{form.gpu}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.soporte.name}}">{{form.soporte.label}}</label>
				{{form.soporte}}
			</div>
		</div>
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<label for="{{form.web_oficial.name}}">{{form.web_oficial.label}}</label>
				{{form.web_oficial}}
			</div>
        </div>
        

        <div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				<button class="btn btn-danger" type="submit">Guardar</button>
			</div>
        </div>
        
	</div>
	


</form>

{% endblock %}

catalogo/templates/videojuego/plataformas_list.html
{% extends 'videojuego/admin.html' %}

{% block title %} Crear Videojuegos {% endblock %}

{% block content %}


<h1 class="text-center text-primary">Filtro Plataformas</h1>

    <br/>
	<div class="row justify-content-center">
                        <div class="col-12 col-md-10 col-lg-8">
                            <form class="card card-sm" action="{% url 'buscar_plataformas' %}" method="GET">
                                {% csrf_token %}
                                <div class="card-body row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <i class="fas fa-search h4 text-body"></i>
                                    </div>

                                    <div class="col">
                                        <input class="form-control form-control-lg form-control-borderless" name="q" type="search" placeholder="Buscar....">
                                    </div>

                                    <div class="col-auto">
                                        <button class="btn btn-lg btn-success" type="submit">Consultar</button>
                                    </div>

                                </div>
                            </form>
                            

                        </div>

    </div>
    <!--<h1 class="text-center text-primary">Lista de Videojuego</h1>-->
    <br>

                            {% if object_list %}
                            <table border="1" cellpadding="8" cellspacing="0" class="table table-bordered">

                                <tr class="bg-secondary text-light">
                                    <td>Marca</td>
                                    <td>Fabricante</td>
                                    <td>Tipo</td>
                                    <td>Generacion</td>
                                    <td>Capacidad de disco</td>
                                    <td>GPU</td>
                                    <!--<td>Soporte</td>-->
                                    <td>Modificacion</td>
                    
                                </tr>
                
                                {% for platformas in object_list %}
                                <tr>
                                    <td>{{ platformas.marca }}</td>
                                    <td>{{ platformas.fabricante }}</td>
                                    <td>{{ platformas.get_tipo_display }}</td>
                                    <td>{{ platformas.generacion }}</td>
                                    <td>{{ platformas.capacidad_disco }}</td>
                                    <td>{{ platformas.gpu }}</td>
                                    <!--<td>{{ platformas.soporte }}</td>-->
                                    
                        
                                    <td>
                                        <a href="{% url 'detalle_plataformas' platformas.id %}" class="btn btn-success">Detalle</a>
                                    </td>
                                   
                                </tr>
                                {% endfor %}
                    
                            </table>
                            {% else %}
                                <h1>Dato no encontrado..</h1>
                            {% endif %}


{% endblock %}

catalogo/templates/videojuego/videojuego_detail.html
{% extends 'videojuego/admin.html' %}

{% block title %} Crear Videojuegos {% endblock %}

{% block content %}

<h1 class="text-center text-primary">Detalle de Videojuego</h1>

<table border="1" cellpadding="8" cellspacing="0" class="table table-bordered">

    <tr>
        <th class="bg-secondary text-light">Nombre</th>
        <td>{{ object.nombre }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Genero</th>
        <td>{{ object.get_genero_display }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Fabricante</th>
        <td>{{ object.fabricante }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Clasificacion</th>
        <td>{{ object.get_clasificacion_display }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Año de Lanzamiento</th>
        <td>{{ object.ano_lanzamiento }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Maximo de Jugadores</th>
        <td>{{ object.max_jugadores }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Jugabilidad</th>
        <td>{{ object.get_jugabilidad_display }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Plataformas</th>
        <td>
            {% for plataforma in videojuego.plataformas.all %}
                {{ plataforma }}<br>
            {% endfor %}
        </td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Web Oficial</th>
        <td><a href="{{ object.web_oficial }}">{{ object.web_oficial }}</a></td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Imagen</th>
        <td>
            {% if object.imagen %}
            <img src="{{ object.imagen.url }}" height="300">
            {% endif %}
        </td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Trailer</th>
        <td><iframe width="560" height="315" src="{{ object.trailer }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></td>
  


                
    </tr>

    <tr>
        <th class="bg-secondary text-light">Raking</th>
        <td>{{ object.ranking }}</td>
    </tr>

    <tr>
        <th class="bg-secondary text-light">Modificacion</th>
        <td>
            <a href="{% url 'actualizar_videojuego' object.id %}" class="btn btn-success">Actualizar</a><br>
            <a href="{% url 'eliminar_videojuego' object.id %}" class="btn btn-danger mt-3">Eliminar</a>
        </td>
    </tr>

</table>

{% endblock %}

catalogo/templates/videojuego/videojuego_list.html
{% extends 'videojuego/admin.html' %}

{% block title %} Crear Videojuegos {% endblock %}

{% block content %}


<h1 class="text-center text-primary">Filtro Videojuego</h1>

    <br/>
	<div class="row justify-content-center">
                        <div class="col-12 col-md-10 col-lg-8">
                            <form class="card card-sm" action="{% url 'search_results' %}" method="GET">
                                {% csrf_token %}
                                <div class="card-body row no-gutters align-items-center">
                                    <div class="col-auto">
                                        <i class="fas fa-search h4 text-body"></i>
                                    </div>

                                    <div class="col">
                                        <input class="form-control form-control-lg form-control-borderless" name="q" type="search" placeholder="Buscar....">
 
                                    </div>

                                    <div class="col-auto p-2">
                                        <label>Género :</label>
                                        <select name="lista">
                                            <option value=""></option>
                                            <option value="a">Acción</option>
                                            <option value="d">Deportes</option>
                                            <option value="e">Estrategia</option>
                                            <option value="c">Carreras</option>
                                        </select>
                                    </div>

                                    <div class="col-auto">
                                        <button class="btn btn-lg btn-success" type="submit">Consultar</button>
                                    </div>

                                </div>
                            </form>
                            

                        </div>

    </div>
    <!--<h1 class="text-center text-primary">Lista de Videojuego</h1>-->
    <br>

                            {% if object_list %}
                            <table border="1" cellpadding="8" cellspacing="0" class="table table-bordered">

                                <tr class="bg-secondary text-light">
                                    <td>Nombre</td>
                                    <td>Genero</td>

                                    <td>Fabricante</td>
                                    
                                    <td>Clasificacion</td>
                                    <!--
                                    <td>Año de Lanzamiento</td>
                                    <td>Maximo de Jugadores</td>
                                    <td>Jugabilidad</td>
                                    -->
                                    <td>Plataformas</td>

                                    <!--<td>Web Oficial</td>-->
                                    <td>Imagen</td>
                                    <!--<td>Trailer</td>-->
                                    <td>Raking</td>
                                    <td>Modificacion</td>
                    
                                </tr>
                
                                {% for videojuego in object_list %}
                                <tr>
                                    <td>{{ videojuego.nombre }}</td>
                                    <td>{{ videojuego.get_genero_display }}</td>
                                    
                                    <td>{{ videojuego.fabricante }}</td>
                                    
                                    <td>{{ videojuego.get_clasificacion_display }}</td>
                                    <!--
                                    <td>{{ videojuego.ano_lanzamiento }}</td>
                                    <td>{{ videojuego.max_jugadores }}</td>
                                    <td>{{ videojuego.get_jugabilidad_display }}</td>
                                    -->
                                    
                                    <td>
                                        {% for plataforma in videojuego.plataformas.all %}
                                            {{ plataforma }}<br>
                                        {% endfor %}
                                    </td>
                                    
                        
                                    <!--<td>{{ videojuego.web_oficial }}</td>-->
                                    <td>
                                        {% if videojuego.imagen %}
                                        <img src="{{ videojuego.imagen.url }}" height="50">
                                        {% endif %}
                                    </td>
                                    <!--<td>{{ videojuego.trailer }}</td>-->
                                    <td>{{ videojuego.ranking }}</td>

                                    
                        
                                    <td>
                                        <a href="{% url 'detalle_videojuego' videojuego.id %}" class="btn btn-success">Detalle</a>
                                    </td>
                                   
                                </tr>
                                {% endfor %}
                    
                            </table>
                            {% else %}
                                <h1>Dato no encontrado..</h1>
                            {% endif %}


{% endblock %}